PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX router: <https://github.com/ColinMaudry/sparql-router#>

delete {
  graph <uri:graph:sparql-router:queries> {
	?query ?p ?o  .
  }
}
where {
  graph <uri:graph:sparql-router:queries> {
  ?query a ?type  ;
    dct:identifier ?slug ;
    ?p ?o .
  }
}
